flaskr/views.py
from flask import (
    Blueprint, flash, g, redirect, render_template, request, url_for
)
from werkzeug.exceptions import abort


from .db import get_db

bp = Blueprint('views', __name__)

@bp.route('/dashboard')
def dashboard():
    db=get_db()
    credit=db.execute(
          ' SELECT sum(MaintenanceFee)'
          ' FROM income'
        ).fetchone()
    debit=db.execute(
           ' SELECT sum(fee)'
           ' FROM expenses'
        ).fetchone()
    residents=db.execute(
           ' SELECT count(Name)'
           ' FROM income'
        ).fetchone()

    list = []

    list.append(credit[0])
    list.append(debit[0])

    return render_template('dashboard.html',list=list,residents=residents)


@bp.route('/')
def index():
    db = get_db()
    posts = db.execute(
        'SELECT p.id, Name,Block,UnitNo,MaintenanceFee,Due'
        ' FROM income p'
         
    ).fetchall()
    return render_template('index.html', posts=posts)

@bp.route('/paid')    
def paid():
    db = get_db()
    posts = db.execute(
        'SELECT p.id, Name,Block,UnitNo,MaintenanceFee,Due'
        ' FROM income p '
        ' WHERE Due=0'
         
    ).fetchall()
    return render_template('paid.html', posts=posts)

@bp.route('/unpaid')     
def unpaid():
    db = get_db()
    posts = db.execute(
        'SELECT p.id, Name,Block,UnitNo,MaintenanceFee,Due'
        ' FROM income p'
        ' WHERE Due>0'
         
    ).fetchall()
    return render_template('unpaid.html', posts=posts)       

@bp.route('/create', methods=('GET', 'POST'))
def create():
    if request.method == 'POST':
        Name = request.form['Name']
        Block = request.form['Block']
        UnitNo = request.form['UnitNo']
        MaintenanceFee = request.form['MaintenanceFee']
        Due = request.form['Due']
        error = None

        if not Name:
            error = 'Name is required.'

        if error is not None:
            flash(error)
        else:
            db = get_db()
            db.execute(
                'INSERT INTO income (Name,Block,UnitNo,MaintenanceFee,Due)'
                ' VALUES (?, ?, ?, ?, ?)',
                (Name,Block,UnitNo,MaintenanceFee,Due)
                
            )
            db.commit()
            return redirect(url_for('views.index'))

    return render_template('create.html')    


@bp.route('/payment/<int:income_id>', methods=('GET', 'POST'))
def payment(income_id):

    db = get_db()
    query = "SELECT Due from income p where p.id = {}".format(income_id) 
    row = db.execute(query).fetchone()
    due = row[0]
    

    if request.method == 'POST':
        amount = int(request.form['amount'])
        error = None

        if error is not None:
            flash(error)
        else:
            db = get_db()
            db.execute(
                'INSERT INTO Payment (income_id,amount)'
                ' VALUES (?, ?)',
                (income_id, amount)
            )
            db.commit()

            due = due - amount

            db.execute(
                'UPDATE income SET due = ? '
                ' WHERE id = ?',
                ( due, income_id)
            )
            db.commit()
            
                

            return redirect(url_for('views.index'))
    
    return render_template('addpayment.html', due=due)  

@bp.route('/history/<int:income_id>')
def history(income_id):
    db=get_db()
    posts=db.execute(
            'SELECT p.id,amount,Pdate'
            ' FROM payment p'
            ' WHERE p.income_id={}'.format(income_id)
        ).fetchall()
    return render_template('history.html', posts=posts)


@bp.route('/vendor')
def vendor():
    db = get_db()
    posts = db.execute(
        'SELECT p.id, Vname,cause,phone,fee'
        ' FROM expenses p'
         
    ).fetchall()
    return render_template('vendor.html', posts=posts)


@bp.route('/vcreate', methods=('GET', 'POST'))
def vcreate():
    if request.method == 'POST':
        Vname = request.form['Vname']
        cause = request.form['cause']
        phone = request.form['phone']
        fee = request.form['fee']
        error = None

        if not Vname:
            error = 'Name is required.'

        if error is not None:
            flash(error)
        else:
            db = get_db()
            db.execute(
                'INSERT INTO expenses (Vname,cause,phone,fee)'
                ' VALUES (?, ?, ?, ?)',
                (Vname,cause,phone,fee)
                
            )
            db.commit()
            return redirect(url_for('views.vendor'))

    return render_template('vcreate.html')    


@bp.route('/salary/<int:expense_id>', methods=('GET', 'POST'))
def salary(expense_id):

    db = get_db()
    query = "SELECT fee from expenses p where p.id = {}".format(expense_id) 
    row = db.execute(query).fetchone()
    due = row[0]
    

    if request.method == 'POST':
        amount = int(request.form['amount'])
        error = None

        if error is not None:
            flash(error)
        else:
            db = get_db()
            db.execute(
                'INSERT INTO salary (expense_id,amount)'
                ' VALUES (?, ?)',
                (expense_id, amount)
            )
            db.commit()

            due = due + amount

            db.execute(
                'UPDATE expenses SET fee = ? ,ispaid=0'
                ' WHERE id = ?',
                ( due, expense_id)
            )
            db.commit()
            
                

            return redirect(url_for('views.vendor'))
    
    return render_template('addpayment.html', due=due)  

@bp.route('/vhistory/<int:expense_id>')
def vhistory(expense_id):
    db=get_db()
    posts=db.execute(
            'SELECT p.id,amount,Pdate'
            ' FROM salary p'
            ' WHERE p.expense_id={}'.format(expense_id)
        ).fetchall()
    return render_template('history.html', posts=posts)


@bp.route('/vpaid')    
def vpaid():
    db = get_db()
    posts = db.execute(
        'SELECT p.id, Vname,cause,phone,fee'
        ' FROM expenses p'
        ' WHERE ispaid=1'
         
    ).fetchall()
    return render_template('vpaid.html', posts=posts)

@bp.route('/vunpaid')     
def vunpaid():
    db = get_db()
    posts = db.execute(
        'SELECT p.id, Vname,cause,phone,fee'
        ' FROM expenses p'
        ' WHERE ispaid=0 '
         
    ).fetchall()
    return render_template('vunpaid.html', posts=posts)

@bp.route('/paynow/<int:expense_id>')
def paynow(expense_id):
    db=get_db()
    posts=db.execute(
        'UPDATE expenses set ispaid=1'
        ' WHERE id={}'.format(expense_id)
        )
    db.commit()
    return redirect(url_for('views.vendor'))

@bp.route('/visitors')
def visitors():
    db=get_db()
    posts=db.execute(
        ' SELECT p.id, visname,category,phoneno,unitno,datein'
        ' FROM visitor p'
    ).fetchall()
    return render_template('visitors.html',posts=posts)

@bp.route('/visitoradd', methods=('GET', 'POST'))
def addvisitor():
    if request.method == 'POST':
        visname = request.form['visname']
        category = request.form['category']
        phoneno = request.form['phoneno']
        unitno = request.form['unitno']
        error = None

        if not visname:
            error = 'Name is required.'

        if error is not None:
            flash(error)
        else:
            db = get_db()
            db.execute(
                'INSERT INTO visitor (visname,category,phoneno,unitno)'
                ' VALUES (?, ?, ?, ?)',
                (visname,category,phoneno,unitno)
                
            )
            db.commit()
            return redirect(url_for('views.visitors'))

    return render_template('addvisitor.html')    

@bp.route('/visitormanage',methods=('GET','POST'))
def manage():
    if request.method == 'POST':
        startdate = request.form['startdate']
        enddate = request.form['enddate']
        error = None

        if not startdate:
            error = 'Date is required.'

        if error is not None:
            flash(error)
        else:
            db = get_db()
            posts=db.execute(
                ' SELECT p.id, visname,category,phoneno,unitno,datein'
                ' FROM visitor p'
                ' WHERE p.datein BETWEEN (?) AND (?)',
                (startdate,enddate)
                
            ).fetchall()
            return render_template('report.html',posts=posts,startdate=startdate,enddate=enddate)

    return render_template('manage.html')
    

flaskr/templates/addpayment.html
{% extends 'base.html' %}


{% block content %}

<h1 class="h3 mb-2 text-gray-800">Payment Details</h1>
<p class="mb-4">Edit your amount</p>



<body>

  <h1> Amount is {{ due }} </h1>

 <form method="post">
 	<div class="form-group">
    <label for="amount">Enter the amount</label>
    <input name="amount" id="amount" value="{{ request.form['amount'] }}" required>
    </div>    
    
    <button class ="btn btn-primary">Save</button>
    <input action="action" class="btn btn-primary" onclick="window.history.go(-1); 
    	return false;" type="submit" value="Cancel"/>
  </form>


	</body>

{% endblock %}  

flaskr/templates/addvisitor.html
{% extends 'base.html' %}


{% block content %}
<h1 class="h3 mb-2 text-gray-800">Visitors Details</h1>
<p class="mb-4">Create Visitor</p>

  


<body>
  <div class="container">
 <form method="post">
  <label for="visname">&emsp;<b>Name : </b> &emsp;&ensp; &nbsp;</label>
    <input name="visname" id="visname" style="width: 150px;" placeholder="Enter the name" value="{{ request.form['visname'] }}" required>
    <br>
    <label for="category">&emsp;<b>Category :</b> &ensp;</label>
    <input name="category" id="category" style="width: 150px;" placeholder="Enter the category" value="{{ request.form['category'] }}"  required>
    <br>
    
    <label for="phoneno">&emsp;<b>Phoneno:</b>&emsp;</label>
    <input name="phoneno" id="phoneno"style="width: 150px;" placeholder="Enter the phoneno" value="{{ request.form['phoneno'] }}" required>
    <br>
    <label for="unitno">&emsp;<b>BlockNo :</b>&nbsp;&ensp;&ensp;</label>
    <input name="unitno" id="unitno" style="width: 150px;" placeholder="Enter the unitno" value="{{ request.form['unitno'] }}" required>
    <br>

    
    
    
    
    <button class ="btn btn-primary" style="margin-left: 19px">Save</button>
    <input action="action" class="btn btn-primary" onclick="window.history.go(-1); 
      return false;" type="submit" value="Cancel"/>

  </form>



  </body>
{% endblock %}  

flaskr/templates/create.html
{% extends 'base.html' %}


{% block content %}
<h1 class="h3 mb-2 text-gray-800">Residents Details</h1>
<p class="mb-4">Create User</p>

  


<body>
  <div class="container">
 <form method="post">
  <label for="Name">&emsp;<b>Name : </b> &emsp;&ensp; &emsp; &emsp;&nbsp;</label>
    <input name="Name" id="Name" style="width: 150px;" placeholder="Enter the name" value="{{ request.form['Name'] }}" required>
    <br>
    <label for="Block">&emsp;<b>Block :</b> &ensp;&emsp; &emsp; &emsp;&nbsp;</label>
    <input name="Block" id="Block" style="width: 150px;" placeholder="Enter the BlockNo" value="{{ request.form['Block'] }}"  required>
    <br>
    <label for="UnitNo">&emsp;<b>UnitNo :</b>&nbsp;&emsp; &emsp; &ensp;&ensp;</label>
    <input name="UnitNo" id="UnitNo" style="width: 150px;" placeholder="Enter the UnitNo" value="{{ request.form['UnitNo'] }}" required>
    <br>
    <label for="MaintenanceFee">&emsp;<b>MaintenanceFee:</b></label>
    <input name="MaintenanceFee" id="MaintenanceFee"style="width: 150px;" placeholder="Enter the MaintenanceFee" value="{{ request.form['MaintenanceFee'] }}" required>
    <br>
    <label for="Due">&emsp;<b>Due :</b> &emsp;&emsp;&emsp;&emsp;&ensp;&nbsp;</label>
    <input name="Due" id="Due" style="width: 150px;" placeholder="Enter the DueAmount" value="{{ request.form['Due'] }}" required>
    <br>
    
    
    
    <button class ="btn btn-primary">Save</button>
    <input action="action" class="btn btn-primary" onclick="window.history.go(-1); 
      return false;" type="submit" value="Cancel"/>

  </form>



	</body>
{% endblock %}  

flaskr/templates/dashboard.html
{% extends 'base.html' %}

{% block content %}

<!-- Header -->

<h1 class="mt-4">Dashboard</h1>
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">Dashboard</li>
</ol>

<div class="d-sm-flex align-items-center justify-content-between mb-4">
  

  <div class="col-xl-3 col-md-6 mb-4">
    <div class="card border-left-primary shadow h-100 py-2">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Total Residents</div>
            <div class="h5 mb-0 font-weight-bold text-gray-800"> {{ residents[0] }} </div>
          </div>
          <div class="col-auto">
            <i class="fas fa-building fa-2x text-gray-300"></i>
          </div>
        </div>
      </div>
    </div>
  </div>


  <div class="col-xl-3 col-md-6 mb-4">
    <div class="card border-left-primary shadow h-100 py-2">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Income </div>
            <div class="h5 mb-0 font-weight-bold text-gray-800">Rs. {{ list[0] }} </div>
          </div>
          <div class="col-auto">
            <i class="fas fa-university fa-2x text-gray-300"></i>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Expenses --> 
  <div class="col-xl-3 col-md-6 mb-4">
    <div class="card border-left-warning shadow h-100 py-2">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-warning text-uppercase mb-1"> Expenses  </div>
            <div class="h5 mb-0 font-weight-bold text-gray-800"> Rs. {{ list[1] }} </div>
          </div>
          <div class="col-auto">
            <i class="fas fa-inr fa-2x text-gray-300"></i>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>


<div class="col-lg-6">
    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-chart-pie mr-1"></i>
            INCOME/EXPENSES 
        </div>
        <div class="card-body"><canvas id="myPieChart" width="100%" height="50"></canvas></div>
        <div class="card-footer small text-muted">Done by GomathyG</div>
    </div>
</div>

{% endblock %}

{% block cusjs %}
<script type="text/javascript">
  // Set new default font family and font color to mimic Bootstrap's default styling
  Chart.defaults.global.defaultFontFamily = '-apple-system,system-ui,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif';
  Chart.defaults.global.defaultFontColor = '#292b2c';

  // Pie Chart Example
  var ctx = document.getElementById("myPieChart");
  var myPieChart = new Chart(ctx, {
    type: 'pie',
    data: {
      labels: ["Income", "Expenses"],
      datasets: [{
        data: {{ list }},
        backgroundColor: ['#007bff', '#dc3545', '#ffc107', '#28a745'],
      }],
    },
  });
</script>

{% endblock %}

flaskr/templates/history.html
{% extends 'base.html' %}


{% block content %}


<body>

<h1 class="h3 mb-2 text-gray-800">History of Payment</h1>
<p class="mb-4">View all the payments made till now  </p>
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary">Payment Table</h6>
  </div>



  <div cla
  ss="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
           <tr>
            <th>ID</th>
            <th>Amount</th>
            <th>Paid Date</th>

             </tr>
        </thead>
        <tbody align="center">
          {% for e in posts %}
          <tr>
            
              <td> {{ e.id }} </td>
              <td>{{ e.amount }} </td> 
              <td>{{ e.Pdate }}</td>

              
             

            </tr>
            {% endfor %}
     </tbody>
     

  </table>  
 </div>
 </div>
 </div> 

</body>

{% endblock %}

flaskr/templates/index.html
{% extends 'base.html' %}


{% block content %}
<body>

<h1 class="h3 mb-2 text-gray-800">Maintenance Fee Details</h1>
<p class="mb-4">View all your residants status of payment  </p>
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary">fee Table</h6>
  </div>

  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Block</th>
            <th>UnitNo</th>
            <th>MaintenanceFee</th>
            <th>Due</th>
            <th>History</th>
            <th>Payment</th>
          </tr>
        </thead>
        <tbody align="center">
          {% for e in posts %}
          <tr>
            
              <td> {{ e.id }} </td>
              <td>{{ e.Name }} </td> 
              <td>{{ e.Block }}</td>
              <td>{{ e.UnitNo }}</td>
              <td>{{ e.MaintenanceFee }}</td>
              <td>{{ e.Due }}</td>

              <td>
              <a href="{{ url_for('views.history', income_id=e.id ) }}" class="btn btn-primary" role="button" >
              View History </a>
            </td>
              <td>
              <a href="{{ url_for('views.payment', income_id=e.id ) }}" class="btn btn-primary" role="button" >
              Enter Payment </a>
            </td>

            </tr>
            {% endfor %}
     </tbody>
     

  </table>  
 </div>
 </div>
 </div> 
<div class="button-group" align="right" >
  <a href="{{ url_for('views.create') }}" class="btn btn-primary" role="button" >
  Create User </a>

</body>

{% endblock %}

flaskr/templates/manage.html
{% extends 'base.html' %}


{% block content %}

<h1 class="h3 mb-2 text-gray-800">Visitors Details</h1>
<p class="mb-4">View visitors between dates</p>

  
  
<style>
  body, input{
    font-family: 'PT Sans',sans-serif;
    font-size: 1.2rem;
    display: block;
    padding: 0.5rem 1rem;
  }
</style>


<body>

  

 <form method="post">
 	<div class="form-group">
    <label for="startdate" >Start date </label>
    <input name="startdate"id="today" type="date" value="{{ request.form['startdate'] }}">
  </div>
    
    <div class="form-group">
      <label for="enddate">End Date</label>
    <input name="enddate" id="today" type="date" value="{{ request.form['enddate']}}">
    </div>

    
    <button class ="btn btn-primary">Submit</button>
    
  </form>
  <script>
    let today=new Date().toISOString().substr(0,10);
    document.querySelector("#today").value=today;
    document.querySelector("#today2").valueAsDate=new Date();
  </script>


	</body>


{% endblock %}  

flaskr/templates/paid.html
{% extends 'base.html' %}


{% block content %}
<body>
<h1 class="h3 mb-2 text-gray-800">Paid Details </h1>
<p class="mb-4">View the list of people who have paid  </p>
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary">Fee Table</h6>
  </div>

  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Block</th>
            <th>UnitNo</th>
            
          </tr>
        </thead>
        <tbody align="center">
          {% for e in posts %}
          <tr>
            
              <td> {{ e.id }} </td>
              <td>{{ e.Name }} </td> 
              <td>{{ e.Block }}</td>
              <td>{{ e.UnitNo }}</td>
              

              
            </tr>
            {% endfor %}
     </tbody>
     

  </table>  
 </div>
 </div>
 </div> 


</body>

{% endblock %}

flaskr/templates/report.html
{% extends 'base.html' %}


{% block content %}
<body>

<h1 class="h3 mb-2 text-gray-800">Visitors Details</h1>
<p class="mb-4">View all the visitors between {{ startdate }} and {{ enddate }}  </p>
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary">Visitor Table</h6>
  </div>

  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Category</th>
            <th>Phoneno</th>
            <th>Unit no</th>
            <th>Date check in</th>
            
          </tr>
        </thead>
        <tbody align="center">
          {% for e in posts %}
          <tr>
            
              <td> {{ e.id }} </td>
              <td>{{ e.visname }} </td> 
              <td>{{ e.category }}</td>
              <td>{{ e.phoneno }}</td>
              <td>{{ e.unitno }}</td>
              <td>{{ e.datein}}</td>
              

              

            </tr>
            {% endfor %}
     </tbody>
     

  </table>  
 </div>
 </div>
 </div> 


</body>

{% endblock %}

flaskr/templates/vcreate.html
{% extends 'base.html' %}


{% block content %}

<h1 class="h3 mb-2 text-gray-800">Vendor Details</h1>
<p class="mb-4">Create new vendor</p>
<div class="card shadow mb-4">
  

<body>
  <div class="container">
 <form method="post">
  <label for="Vname">&emsp;<b>Name : </b> &emsp;&emsp; &emsp;&nbsp;</label>
    <input name="Vname" id="Vname" style="width: 150px;" placeholder="Enter the name" value="{{ request.form['Vname'] }}" required>
    <br>
    <label for="cause">&emsp;<b>Department :</b>&emsp;</label>
    <input name="cause" id="cause" style="width: 150px;" placeholder="Enter the department" value="{{ request.form['cause'] }}"  required>
    <br>
    <label for="phone">&emsp;<b>PhoneNo :</b>&nbsp;&emsp;  &ensp;</label>
    <input name="phone" id="phone" style="width: 150px;" placeholder="Enter the phoneNo" value="{{ request.form['phone'] }}" required>
    <br>
    <label for="fee">&emsp;<b>Salary:</b>&emsp;&emsp;&emsp;&emsp;</label>
    <input name="fee" id="fee"style="width: 150px;" placeholder="Enter the fee" value="{{ request.form['fee'] }}" required>
    
    <br>
    <br>
       
    <button class ="btn btn-primary" style="margin-left: 19px">Save</button>
    <input action="action" class="btn btn-primary" onclick="window.history.go(-1); 
      return false;" type="submit" value="Cancel"/>
  </form>
</div>


  </body>
{% endblock %}  

flaskr/templates/vendor.html
{% extends 'base.html' %}


{% block content %}
<body>

<h1 class="h3 mb-2 text-gray-800">Expenses Details</h1>
<p class="mb-4">View all the expenses made till now  </p>
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary">Expense Table</h6>
  </div>

  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Vendor</th>
            <th>Phoneno</th>
            <th>Amount</th>
            <th>Bonus</th>
          </tr>
        </thead>
        <tbody align="center">
          {% for e in posts %}
          <tr>
            
              <td> {{ e.id }} </td>
              <td>{{ e.Vname }} </td> 
              <td>{{ e.cause }}</td>
              <td>{{ e.phone }}</td>
              <td>{{ e.fee }}</td>
              

              <!--<td>
              <a href="{{ url_for('views.vhistory', expense_id=e.id ) }}" class="btn btn-primary" role="button" >
              View History </a>
            </td>-->
              <td>
              <a href="{{ url_for('views.salary', expense_id=e.id ) }}" class="btn btn-primary" role="button" >
              Edit </a>
            </td>

            </tr>
            {% endfor %}
     </tbody>
     

  </table>  
 </div>
 </div>
 </div> 
<div class="button-group" align="right" >
  <a href="{{ url_for('views.vcreate') }}" class="btn btn-primary" role="button" >
  Add Vendor </a>

</body>

{% endblock %}

flaskr/templates/visitors.html
{% extends 'base.html' %}


{% block content %}
<body>

<h1 class="h3 mb-2 text-gray-800">Visitors Details</h1>
<p class="mb-4">View all the visitors till now  </p>
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary">Visitor Table</h6>
  </div>

  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Category</th>
            <th>Phoneno</th>
            <th>Block no</th>
            <th>Date check in</th>
            
          </tr>
        </thead>
        <tbody align="center">
          {% for e in posts %}
          <tr>
            
              <td> {{ e.id }} </td>
              <td>{{ e.visname }} </td> 
              <td>{{ e.category }}</td>
              <td>{{ e.phoneno }}</td>
              <td>{{ e.unitno }}</td>
              <td>{{ e.datein}}</td>
              

              

            </tr>
            {% endfor %}
     </tbody>
     

  </table>  
 </div>
 </div>
 </div> 
<div class="button-group" align="right" >
  <a href="{{ url_for('views.addvisitor') }}" class="btn btn-primary" role="button" >
  Add Visitor </a>

</body>

{% endblock %}

flaskr/templates/vpaid.html
{% extends 'base.html' %}


{% block content %}
<body>
<h1 class="h3 mb-2 text-gray-800">Unpaid Details </h1>
<p class="mb-4">View the list of all workers whose salary has been paid  </p>
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary">Fee Table</h6>
  </div>

  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Department</th>
            <th>Salary</th>
            
            
          </tr>
        </thead>
        <tbody align="center">
          {% for e in posts %}
          <tr>
            
              <td> {{ e.id }} </td>
              <td>{{ e.Vname }} </td> 
              <td>{{ e.cause }}</td>
              <td>{{ e.fee }}</td>

              
         
            </tr>
            {% endfor %}
     </tbody>
     

  </table>  
 </div>
 </div>
 </div> 

</body>

{% endblock %}

flaskr/templates/vunpaid.html
{% extends 'base.html' %}


{% block content %}
<body>
<h1 class="h3 mb-2 text-gray-800">Unpaid Details </h1>
<p class="mb-4">View the list of all people whose amount has to be paid  </p>
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary">Fee Table</h6>
  </div>

  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Department</th>
            <th>PhoneNo</th>
            <th>Salary</th>
            <th>Pay</th>
            
          </tr>
        </thead>
        <tbody align="center">
          {% for e in posts %}
          <tr>
            
              <td> {{ e.id }} </td>
              <td>{{ e.Vname }} </td> 
              <td>{{ e.cause }}</td>
              <td>{{ e.phone }}</td>
              <td>{{ e.fee }}</td>

              <td>
              <a href="{{ url_for('views.paynow', expense_id=e.id ) }}" class="btn btn-primary" role="button" >
              Pay  </a>
            </td>
         
            </tr>
            {% endfor %}
     </tbody>
     

  </table>  
 </div>
 </div>
 </div> 

</body>

{% endblock %}